name: valentine
description: "A Valentine maker"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  # navigation
  go_router: ^18.0.2

  # theme
  theme_tailor_annotation: ^4.0.0
  google_fonts: ^9.0.0

  # sound
  flame_audio: ^2.12.2
  audioplayers: ^6.8.1

  # drawing
  flutter_painter_v2: ^2.1.1
  image: ^4.10.1

  # responsive
  responsive_framework: ^1.5.1

  # platform
  share_plus: ^13.3.1
  file_picker: ^13.1.0
  path_provider: ^2.1.6
  url_launcher: ^6.3.3

  # state
  provider: ^6.1.5+1

  # monitor
  sentry_flutter: ^8.14.2
  firebase_analytics: ^12.6.0
  firebase_core: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^13.3.0
  build_runner: ^2.16.1
  flutter_lints: ^6.0.0
  theme_tailor: ^4.0.1
  sentry_dart_plugin: ^3.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/sounds/
    - assets/images/
    - assets/images/maker/
    - assets/images/maker/toolbar/
    - assets/images/maker/faces/
    - assets/images/maker/stickers/
    - assets/images/onboarding/
    - assets/images/onboarding/floating/

sentry:
  upload_debug_symbols: false
  upload_source_maps: true
  upload_sources: false
  wait_for_processing: false
  log_level: error # possible values: trace, debug, info, warn, error
  commits: auto
  ignore_missing: true
